apiVersion: v1
kind: Service
metadata:
    name: "sreejacluster-725a"
    labels:
        app: "sreejacluster-725a"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "sreejacluster-725a"