on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: sreejacontainerregistry.azurecr.io
        username: ${{ secrets.acr_sreejacontainerregistry_username }}
        password: ${{ secrets.acr_sreejacontainerregistry_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t sreejacontainerregistry.azurecr.io/sreejacluster:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push sreejacontainerregistry.azurecr.io/sreejacluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_sreejacluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep sreejacluster9acf | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace sreejacluster9acf`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: sreejacluster9acf
        container-registry-url: sreejacontainerregistry.azurecr.io
        container-registry-username: ${{ secrets.acr_sreejacontainerregistry_username }}
        container-registry-password: ${{ secrets.acr_sreejacontainerregistry_password }}
        secret-name: sreejaclustedockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: sreejacluster9acf
        manifests: |
          manifests/deployment-3.yml
          manifests/service-3.yml
        images: |
          sreejacontainerregistry.azurecr.io/sreejacluster:${{ github.sha }}
        imagepullsecrets: |
          sreejaclustedockerauth
